SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO AS A, ITEM_INFO AS B, ITEM_TREE AS C
WHERE A.ITEM_ID = C.ITEM_ID && C.PARENT_ITEM_ID = B.ITEM_ID
        && B.RARITY = "RARE"
ORDER BY A.ITEM_ID DESC;